image: ubuntu:18.04

stages:
  - build

debug:
  stage: build
  variables:
    COMPILE_MODE: Debug
  before_script:
    - ./prep-gitlab.sh
  script:
    - ./buildstrap.sh ${COMPILE_MODE};
  artifacts:
    paths:
      - angle/out/Debug/lib*.so
      - angle/out/Debug/args.gn

release:
  stage: build
  variables:
    COMPILE_MODE: Release
  before_script:
    - ./prep-gitlab.sh
  script:
    - ./confstrap.sh ${COMPILE_MODE};
  artifacts:
    paths:
      - angle/out/Release/lib*.so
      - angle/out/Release/args.gn
