image: cybik/anglestrap:latest

stages:
  - build

.build_def: &build_definition
  stage: build
  artifacts:
    paths:
      - angle/out/*/lib*.so
      - angle/out/*/args.gn
  before_script:
    - ./prep-gitlab.sh
    

.build_def_normal: &build_definition_normal
  <<: *build_definition
  script: |
    echo "Buildstrapping for ${CI_JOB_NAME}";
    ./buildstrap.sh ${CI_JOB_NAME};

.build_def_ggp: &build_definition_ggp
  <<: *build_definition
  script: |
    echo "Buildstrapping for ${CI_JOB_NAME} ggp";
    ./buildstrap.sh ${CI_JOB_NAME} ggp;

Debug:
  variables:
    TARGET: Debug
  <<: *build_definition-normal

Release:
  variables:
    TARGET: Release
  <<: *build_definition-normal

Debug-ggp:
  variables:
    TARGET: Debug
  <<: *build_definition-ggp

Release-ggp:
  variables:
    TARGET: Release
  <<: *build_definition-ggp
