image: ubuntu:18.04

debug:
  stage: build
  before_script:
    - ./prep-gitlab.sh
  script:
    - ./buildstrap-Debug.sh
  artifacts:
    paths:
      - angle/out/Debug/lib*.so
      - angle/out/Debug/args.gn

release:
  stage: build
  before_script:
    - ./prep-gitlab.sh
  script:
    - ./buildstrap-Release.sh
  artifacts:
    paths:
      - angle/out/Release/lib*.so
      - angle/out/Release/args.gn
