image: cybik/anglestrap:latest

stages:
  - build

.build_def: &build_definition
  stage: build
  artifacts:
    paths:
      - angle/out/*/lib*.so
      - angle/out/*/args.gn
  before_script:
    - ./prep-gitlab.sh
  script: |
    echo "Buildstrapping for ${CI_JOB_NAME}";
    ./buildstrap.sh ${CI_JOB_NAME};

# the job names MUST MATCH THE ANGLE BUILD TYPES.
#  You have been SO WARNED.
Debug:
  <<: *build_definition

Release:
  <<: *build_definition
