image: ubuntu:18.04

debug:
  stage: build
  before_script:
    - apt update && apt -y install git curl wget python sudo lsb-release ninja-build
  script:
    - ./bootstrap-debug.sh
    - cd angle && ninja -C out/Debug
  artifacts:
    paths:
      - angle/out/Debug/libGLES*.so
      - angle/out/Debug/libEGL.so

release:
  stage: build
  before_script:
    - apt update && apt -y install git curl wget python sudo lsb-release ninja-build
  script:
    - ./bootstrap-release.sh
    - cd angle && ninja -C out/Release
  artifacts:
    paths:
      - angle/out/Release/libGLES*.so
      - angle/out/Release/libEGL.so
