language: cpp
os:
  - linux
  - osx

dist: bionic
addons:
  apt:
    packages:
      - git
      - curl
      - wget
      - python
      - sudo
      - lsb-release
      - ninja-build
compiler:
  - gcc
  - clang

env: 
  - NATURE=Debug
  - NATURE=Release

matrix:
  exclude:
    - os: osx
      compiler: gcc 

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./buildstrap-${NATURE}.sh; fi

branches:
  only:
    - master