language: cpp
os:
  - linux
dist: bionic

compiler:
  - gcc

addons:
  apt:
    packages:
      - git
      - curl
      - wget
      - python
      - sudo
      - lsb-release

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime; export DEBIAN_FRONTEND=noninteractive; apt -y install tzdata; fi

script:
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo "Nope right now"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./bootstrap-debug.sh; fi