language: cpp
os:
  - linux
dist: bionic

compiler:
  - gcc

addons:
  apt:
    packages:
      - git
      - curl
      - wget
      - python
      - sudo
      - lsb-release
      - ninja-build

script:
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo "Nope right now"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./bootstrap-debug.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ls; ls angle; ls angle/out; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd angle; ninja -C out/Debug; fi