name: cronjob

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
    steps:
    - uses: actions/checkout@v1
    - name: Environment bootstrap
      run: sudo ./prep-gitlab.sh
    - name: Build ANGLE
      run: ./buildstrap-Debug.sh
