name: Matrixed Build

on: 
  push:
    branches: master, testWindowsBranch
  schedule:
  - cron: "0 0 * * *"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        target: [ggp, linux]
        variant: [Release]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }} - ${{ matrix.variant }} on ${{ matrix.os }}
    steps:
    - name: Check out source
      uses: actions/checkout@v1
    - name: Environment bootstrap
      run: sudo ./prep-gitlab.sh
    - name: Bootstrap ${{ matrix.variant }} ANGLE environment for ${{ matrix.target }} on ${{ matrix.os }}  
      run: ./bootstrap-moded.sh ${{ matrix.variant }} ${{ matrix.target }}
    - name: Archive ${{ matrix.variant }} ANGLE configuration for ${{ matrix.target }} on ${{ matrix.os }}  
      uses: actions/upload-artifact@master
      with:
        name: Configuration of ${{ matrix.variant }} for ${{ matrix.target }} on ${{ matrix.os }}  
        path: angle/out/${{ matrix.variant }}/args.gn
    - name: Fake out the GGP headers
      if: matrix.target == 'ggp'
      run: echo "Moved to a script. Just keeping this BECAUSE I LIKE CONDITIONAL STEPS this is so cool"
    - name: Build ANGLE ${{ matrix.variant }} for ${{ matrix.target }} on ${{ matrix.os }}  
      run: ./makestrap.sh ${{ matrix.variant }}
    - name: Compress ${{ matrix.variant }} artifacts for ${{ matrix.target }} on ${{ matrix.os }}  
      run: |
        cd angle/out/${{ matrix.variant }};
        tar -cf ../${{ matrix.variant }}.tar *.so;
        gzip ../${{ matrix.variant }}.tar;
    - name: Archive ANGLE ${{ matrix.variant }} Build Artifacts for ${{ matrix.target }} on ${{ matrix.os }}  
      uses: actions/upload-artifact@master
      with:
        name: Angle ${{ matrix.variant }} Libraries for ${{ matrix.target }} on ${{ matrix.os }}
        path: angle/out/${{ matrix.variant }}.tar.gz
