name: Release Build on Commit

on: [push]

jobs:
  build-linux-release:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        target: [ggp, linux]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out source
      uses: actions/checkout@v1
    - name: Environment bootstrap
      run: sudo ./prep-gitlab.sh
    - name: Build ANGLE
      run: |
        chmod 755 ./buildstrap-Release-arg.sh;
        ./buildstrap-Release-arg.sh ${{ matrix.target }}
    - name: Compress artifacts
      run: |
        cd angle/out/Release;
        tar -cf ../Release.tar *.so;
        gzip ../Release.tar;
    - name: Archive artifacts
      uses: actions/upload-artifact@master
      with:
        name: Angle Libraries
        path: angle/out/Release.tar.gz
