name: Matrixed Windows Build

on: 
  workflow_dispatch:
    inputs:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  windows:
    strategy:
      matrix:
        os: [windows-2019]
        variant: [Release]
        arch: [32, 64]
        include:
          - os: windows-2019
            arch: 32
            cpu: x86
          - os: windows-2019
            arch: 64
            cpu: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.variant }} on ${{ matrix.os }} ( ${{ matrix.cpu }}_${{ matrix.arch }} )
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: '0'
      DEPOT_TOOLS_METRICS: '0'
      PYTHON_HOME: ''
    steps:
      - name: Check out source
        uses: actions/checkout@v1
      - name: Fetch depot_tools
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://storage.googleapis.com/chrome-infra/depot_tools.zip" -OutFile depot_tools.zip
          &7z x depot_tools.zip -odepot_tools
          Remove-Item depot_tools.zip
      - name: Config depot_tools
        shell: pwsh
        run: |
            $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
            $env:Path = "$pwd\depot_tools;" + $env:Path
            cd depot_tools
            ./update_depot_tools.bat
            dir
      - name: Get Angle Sauce
        shell: pwsh
        run: |
          del C:\ProgramData\Chocolatey\bin\pytho*.exe
          git clone https://chromium.googlesource.com/angle/angle
          cd angle
      - name: Bootstrap ${{ matrix.variant }} ANGLE dependencies on ${{ matrix.os }}
        shell: pwsh
        run: |
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
          $env:Path = "$pwd\depot_tools;" + $env:Path
          refreshenv
          cd angle
          python scripts\bootstrap.py
          refreshenv
          gclient sync
      - name: Set up build projects
        shell: pwsh
        run: |
          choco install llvm 2>&1>$null
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
          $env:Path = "$pwd\depot_tools;" + $env:Path
          cd angle
          gn gen out/Build_${{ matrix.arch }} --args='is_clang=true is_debug=false use_custom_libcxx=true is_component_build=false target_cpu=\"${{ matrix.cpu }}\" angle_enable_swiftshader=false'
      - name: Build Angle
        shell: pwsh
        run: |
          $env:Path = "$pwd\depot_tools;" + $env:Path
          &("C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat")
          cd angle
          autoninja -C out\Build_${{ matrix.arch }} libEGL
          autoninja -C out\Build_${{ matrix.arch }} libGLESv2
      - name: Copy Binaries
        shell: pwsh
        run: |
          New-Item -Name "${{ matrix.cpu }}" -ItemType "directory"
          New-Item -Name "lib" -ItemType "directory"
          New-Item -Name "Binaries" -ItemType "directory"
          Copy-Item -Path "angle\out\Build_${{ matrix.arch }}\*.lib" -Destination "${{ matrix.cpu }}" -Recurse
          Copy-Item -Path "angle\out\Build_${{ matrix.arch }}\*.dll" -Destination "${{ matrix.cpu }}" -Recurse
          Copy-Item -Path "angle\out\Build_${{ matrix.arch }}\*.pdb" -Destination "${{ matrix.cpu }}" -Recurse
          Move-Item -Path "${{ matrix.cpu }}" -Destination "lib"
          Move-Item -Path "lib" -Destination "Binaries"
          Copy-Item -Path "angle\include" -Destination "Binaries" -Recurse 
          7z a ANGLE.zip Binaries\*
      - name: Archive ${{ matrix.variant }} ANGLE archive on ${{ matrix.os }}
        uses: actions/upload-artifact@master
        with:
          name: Angle ${{ matrix.cpu }}_${{ matrix.arch }} Libraries for ${{ matrix.variant }} on ${{ matrix.os }}
          path: Angle.zip
